module_poll = "Poll"
poll_sidebar = "Poll: %s (%s)"
question = "Question"
max_answers = "Max Answers"
choices = "Choices"
poll_outcome = "%d) %s (%s)"

##########
# Create #
##########
mt_poll_create = "Create Poll"
md_poll_create = "Create a new Poll and broadcast it."
msg_poll_created = "Your Poll has been created."
add_choice = "Add choice"

########
# Mail #
########
mt_poll_mail = "Mail Poll"
md_poll_mail = "Cronjob mailing new polls."
mails_poll_created = "Global Poll: %s"
mailb_poll_created = "Hello %s<br/>\nThere is a new poll on %s.<br/>\n<br/>\n%s<br/>\n%s<br/>\n<br/>\n<br/>\nYou can vote via these links:<br/>\n<br/>%s<br/>\n<br/>\nKind Regards<br/>\nThe %2$s System."

#############
# Vote Poll #
#############
choice = "Choice %d: %s"
mt_poll_vote = "Vote Poll"
md_poll_vote = "Vote for a poll."
err_poll_max_chosen = "You may only select up to %d choices."
err_poll_min_chosen = "You have to select at least %d choices."
msg_poll_voted = "Your vote has been registered."

########
# Show #
########
mt_poll_show = "Poll"
md_poll_show = "View a poll on this website."

############
# Announce #
############
mt_poll_announce = "Poll Announcer"
md_poll_announce = "Send poll announcements from IPC. Subscribe channels for poll announcements. Users have a user setting."
msg_poll_announce = "New Global Poll: %s %s - Vote with $pv %s **1** <n> [<n>]. Choices: %s. Example $pv **%s** 1."
